# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: kaihong:kaihong-coder-14b
clients:
- type: openai-compatible
  name: kaihong
  api_base: http://218.17.51.10:3010/v1
  api_key: sk-AGBByVqDmrNWMqMV5e984d624cD944A7A53fAb4486282a54
  models:
  - name: kaihong-coder-14b
